Api end points
monicah79/Bloggers-app pull request #10
Opened 2023-05-12 03:25 UTC by monicah79

- Created an API endpoint to list all posts for a user.
- Created an API endpoint to list all comments for a user's post.
- Created an API endpoint to add a comment to a post. Remember that the owner of the comment is the user that makes it; it should not be set by passing a parameter.
*Your API endpoints should receive JSON and respond JSON as well.

![image](https://github.com/monicah79/Bloggers-app/assets/107432779/02cc63ea-e736-4187-b0cb-ab082b9cad6c)
![image](https://github.com/monicah79/Bloggers-app/assets/107432779/4a048f66-c0f1-44d3-b971-9cb87d56c235)

2023-05-12 03:33 UTC, monicah79 commented
![image](https://github.com/monicah79/Bloggers-app/assets/107432779/268ac58a-baab-418a-b7c6-ceadfe580969)

2023-05-12 03:51 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @monicah79,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-12 03:51 UTC, Omar-Muhamad commented on config/routes.rb
> +  end
- [ ] When I try to signup to add data the test your API endpoints I can't because It throws the error below, Please fix that.

![image](https://github.com/monicah79/Bloggers-app/assets/68796232/0348656a-867b-41b1-ae1c-ed7407ce71db)

And Kindly add the proper instructions on how to test your endpoints in the PR description.

2023-05-12 03:52 UTC, Omar-Muhamad commented
Hi @monicah79,
After you ask for a review to your project,
Kindly don't push any changes until you get the review from the code reviewer.
Have a great day 😊

2023-05-12 03:54 UTC, monicah79 commented
Noted and Thank you

On Fri, 12 May 2023 at 06:52, Omar Muhammad ***@***.***>
wrote:

> Hi @monicah79 <https://github.com/monicah79>,
> After you ask for a review to your project,
> Kindly don't push any changes until you get the review from the code
> reviewer.
> Have a great day 😊
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/monicah79/Bloggers-app/pull/10#issuecomment-1545068606>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZTUWS6WNMDDVC5VRDUWGRDXFWXWZANCNFSM6AAAAAAX66KWMQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-12 15:47 UTC, TadesseDev requested changes
### Hi @monicah79 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [x] Good job making most of the changes requested by the previous reviewer. 🙏


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
-N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 15:47 UTC, TadesseDev commented on app/controllers/api/comment_controller.rb
> +  end
- [ ] Good job setting the user before adding the comment @monicah79, But we also need to set the post before using it. I notice you have ` before_action :set_user, only: %i[show create]` but I could not find the `set_post` method. Please make sure the post is set before being used.

2023-05-12 15:47 UTC, TadesseDev commented on app/controllers/user_controller.rb
>    def index
- [ ] Dear @monicah79, After signing up for your application, It keeps redirecting to the login page where I could not log in with the registration detail. Please make sure the user can register for the application. This also prevents me from checking other functionality of the application.

### Please make sure all the functionalities are in place before the next review request. 
https://github.com/monicah79/Bloggers-app/assets/69077061/d29cc207-26c3-4932-b023-5105f0ba099b

2023-05-13 17:00 UTC, BenMukebo approved these changes
### Hi @monicah79, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

### To Highlight :1st_place_medal: 
- All API endpoints receives JSON and responds in a JSON format as well. :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 17:04 UTC, merged